name: Java JAR CI with Maven & Tests

on:
  push:
    branches: [ "**", "!release" ]
  pull_request:
    branches: [ "**", "!release" ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build with Maven
        run: ./mvnw -B package
      - name: Dump Target
        run: ls -al target
